import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "premium-membership",
    title: "Premium Membership",
    description: "Akses penuh ke semua fitur premium selama 30 hari.",
    longDescription:
      "Nikmati pengalaman terbaik dengan Premium Membership. Dapatkan akses tak terbatas ke semua konten eksklusif, item khusus, dan keuntungan yang tidak tersedia untuk pengguna reguler.",
    category: "Membership",
    image: "https://images.pexels.com/photos/7681091/pexels-photo-7681091.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/7681091/pexels-photo-7681091.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/7681093/pexels-photo-7681093.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/7681094/pexels-photo-7681094.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 49000,
    oldPrice: 99000,
    discount: 50,
    featured: true,
    features: [
      "Akses semua fitur premium",
      "Item eksklusif bulanan",
      "Prioritas customer support",
      "Tanpa iklan",
    ],
    includes: ["30 hari Premium", "1 Exclusive Skin", "500 Diamond Bonus"],
    badge: "Best Seller",
  },
  {
    id: "diamond-bundle-s",
    title: "Diamond Bundle S",
    description: "500 Diamond + bonus 50 Diamond eksklusif.",
    longDescription:
      "Paket hemat untuk penggemar Diamond! Dapatkan 500 Diamond reguler plus 50 Diamond bonus yang hanya tersedia melalui bundle ini.",
    category: "Bundles",
    image: "https://images.pexels.com/photos/6210765/pexels-photo-6210765.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/6210765/pexels-photo-6210765.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/6210766/pexels-photo-6210766.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 75000,
    oldPrice: 120000,
    discount: 38,
    featured: true,
    features: ["500 Diamond", "50 Diamond Bonus", "Instant delivery", "Permanent ownership"],
    includes: ["500 Diamond", "50 Bonus Diamond"],
    badge: "Hot Deal",
  },
  {
    id: "diamond-100",
    title: "100 Diamond",
    description: "Top up 100 Diamond dengan harga terbaik.",
    longDescription:
      "Butuh Diamond tambahan dengan cepat? Top up 100 Diamond langsung ke akunmu dengan harga kompetitif.",
    category: "Diamond",
    image: "https://images.pexels.com/photos/8442306/pexels-photo-8442306.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/8442306/pexels-photo-8442306.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 15000,
    featured: false,
    features: ["100 Diamond", "Instant delivery", "No expiry"],
    includes: ["100 Diamond"],
  },
  {
    id: "diamond-500",
    title: "500 Diamond",
    description: "Paket besar 500 Diamond hemat.",
    longDescription:
      "Lebih banyak Diamond, lebih banyak hemat. Dapatkan 500 Diamond sekaligus untuk semua kebutuhan in-game kamu.",
    category: "Diamond",
    image: "https://images.pexels.com/photos/8442306/pexels-photo-8442306.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/8442306/pexels-photo-8442306.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 65000,
    oldPrice: 75000,
    discount: 13,
    featured: false,
    features: ["500 Diamond", "Instant delivery", "No expiry"],
    includes: ["500 Diamond"],
  },
  {
    id: "summer-event-pass",
    title: "Summer Event Pass",
    description: "Pass eksklusif untuk Summer Event 2025.",
    longDescription:
      "Jangan lewatkan Summer Event 2025! Dapatkan akses ke misi eksklusif, reward harian, dan skin terbatas hanya dengan Event Pass.",
    category: "Event",
    image: "https://images.pexels.com/photos/620037/pexels-photo-620037.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/620037/pexels-photo-620037.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/620038/pexels-photo-620038.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 35000,
    oldPrice: 59000,
    discount: 41,
    featured: true,
    features: ["20+ Exclusive missions", "Daily rewards", "Limited summer skin", "Event badge"],
    includes: ["Event Pass", "Summer Skin", "200 Diamond"],
    badge: "Limited",
  },
  {
    id: "legendary-bundle",
    title: "Legendary Bundle",
    description: "Bundle terlengkap: skin, diamond, dan membership.",
    longDescription:
      "Paket terbaik value untuk pemain serius! Dapatkan Legendary Skin, 1000 Diamond, dan 30 hari Premium Membership dalam satu bundle.",
    category: "Bundles",
    image: "https://images.pexels.com/photos/7773162/pexels-photo-7773162.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/7773162/pexels-photo-7773162.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 199000,
    oldPrice: 350000,
    discount: 43,
    featured: true,
    features: [
      "1 Legendary Skin",
      "1000 Diamond",
      "30 hari Premium",
      "Exclusive emote",
    ],
    includes: ["Legendary Skin", "1000 Diamond", "30 Days Premium"],
    badge: "Best Value",
  },
  {
    id: "gift-card-50",
    title: "Gift Card 50K",
    description: "Kirim hadiah ke teman dengan Gift Card 50K.",
    longDescription:
      "Ingin memberi hadiah ke teman? Gift Card 50K dapat dikirim langsung ke akun temanmu sebagai hadiah spesial.",
    category: "Gift",
    image: "https://images.pexels.com/photos/6213994/pexels-photo-6213994.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/6213994/pexels-photo-6213994.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 50000,
    featured: false,
    features: ["Send to friend", "Custom message", "No expiry", "Instant delivery"],
    includes: ["50K Gift Card"],
  },
  {
    id: "limited-skin-pack",
    title: "Limited Skin Pack",
    description: "3 skin eksklusif edisi terbatas.",
    longDescription:
      "Koleksi 3 skin eksklusif yang hanya tersedia musim ini. Setelah musim berakhir, skin ini tidak akan pernah dijual lagi!",
    category: "Limited",
    image: "https://images.pexels.com/photos/7773162/pexels-photo-7773162.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/7773162/pexels-photo-7773162.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 89000,
    oldPrice: 150000,
    discount: 41,
    featured: false,
    features: ["3 Exclusive skins", "Seasonal limited", "Animated effects", "Unique loading screen"],
    includes: ["3 Limited Skins"],
    badge: "Limited",
  },
  {
    id: "weekly-diamond-deal",
    title: "Weekly Diamond Deal",
    description: "250 Diamond + 30 bonus setiap minggu.",
    longDescription:
      "Langganan mingguan Diamond dengan harga spesial. Otomatis mendapat 250 Diamond + 30 bonus setiap minggu.",
    category: "Popular",
    image: "https://images.pexels.com/photos/8442306/pexels-photo-8442306.jpeg?auto=compress&cs=tinysrgb&w=800",
    gallery: [
      "https://images.pexels.com/photos/8442306/pexels-photo-8442306.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    price: 30000,
    oldPrice: 40000,
    discount: 25,
    featured: false,
    features: ["250 Diamond weekly", "30 Bonus Diamond", "Auto-renew option", "Cancel anytime"],
    includes: ["250 Diamond/week", "30 Bonus Diamond"],
  },
];
